### ISSUE TITLE
bug: Biased random generator

### ISSUE THREAD

**Issue by kchalkias** [firelotto/firelotto#2]
Based on one of our [research scientific posts](https://www.linkedin.com/pulse/why-firelottos-blockchain-based-random-engine-fair-kostas-chalkias/), the utilised random generation algorithm is biased (modulo bias) and the distribution is skewed, favouring the smaller numbers.

The modulo operation is performed between the numbers’ decreasing list length and the the next byte. At this stage, we can detect a modulo bias issue, because: 
- _n_ does not divide 256.
- even if it did, _n_ is constantly decreasing in each iteration and apparently some of them if not all won’t divide 256.

**Comment by polovaikin** [comment]
This shift does not give advantage to those players who fill in their lottery tickets starting from the left side.
We have developed our RNG algorithm taking into account the limitations of Ethereum smart contracts and the lottery rules.
According to the rules of the 4/20 lottery, you need to match 4 numbers out of 20 to win the jackpot. It is possible to win the jackpot in this type of lottery by filling in lottery tickets with all 4,845 possible number combinations. It means that tampering with the RNG should be analyzed over a period of time not exceeding 4,845 lottery drawings because otherwise it does not give the player any advantage over some other player who has filled in lottery tickets with all possible combinations.
Your graph covers 2^32 = 4,294,967,296 drawings.
Here is a graph showing the probability of drawing any of the numbers from 1 to 20 over 5,000 drawings (2 runs):
![img-2018-01-25-16-21-06](https://user-images.githubusercontent.com/1670469/35473274-e25bf0f0-038e-11e8-9b68-82c68bbd4d62.png)
 
According to the rules of the lottery, matching only one number will not bring the player any winnings. At least two numbers should be matched.
The following graph shows how many times the combinations of two numbers will be drawn over 5,000 drawings (2 runs):
![img-2018-01-25-16-07-28](https://user-images.githubusercontent.com/1670469/35473275-ed48df46-038e-11e8-9ffd-c11c0b6330da.png)
 
No significant shifts can be seen over these periods of time.
If there are bigger number combinations and an increase in the total number of combinations in other lotteries, the effect of the modulus shift decreases.

**Comment by carlossusX** [comment]
Could you not just use more bytes from the hash to randomise the order of the numbers in the array before picking the winning numbers?

**Comment by polovaikin** [comment]
Yes, we can. But now this is not necessary.
